"""
Provue Telemetry Console (edge service)
=======================================

Public-facing dashboard/API for the Provue telemetry platform. It issues
session tokens, exposes a small documented API surface, and can render a
"report" by fetching an approved telemetry source server-side.

Intentionally vulnerable for the CTF, along two independent axes:

  1. Session issuance mass-assignment: the token claims are built by merging
     the raw request body, so a caller can promote themselves to `operator`.
  2. Report render SSRF: the "approved source" allowlist is checked with a
     naive substring test, which a URL with a userinfo component defeats,
     letting the caller pivot the server-side fetch to the internal collector.

Neither bug alone reaches the flag; the intended path chains them.
"""
import json
import os
from urllib.parse import urlsplit, urlunsplit

import jwt
import requests
from flask import Flask, Response, jsonify, request

app = Flask(__name__)

JWT_SECRET = os.environ.get("JWT_SECRET", "provue-edge-hs256-6d1e9f0a")
JWT_ALG = "HS256"
EDGE_ORIGIN_TOKEN = os.environ.get("EDGE_ORIGIN_TOKEN", "edge-origin-2f9c1a7b4e")

# The production deploy key. Its authoritative copy lives in the collector's
# private telemetry store; the edge tier keeps a matching copy to authorise
# publishing a report. Presenting the correct key to /api/reports/publish
# releases the flag -- so an attacker must first exfiltrate the key from the
# collector (via the SSRF + search chain) and then reuse it here.
DEPLOY_KEY = os.environ.get("DEPLOY_KEY", "k-9f3a1c7b19e4d20a")
FLAG = os.environ.get("FLAG", "flag{ssrf_pivot_collector_search_7b19e4}")

# The only host an operator is *supposed* to be able to render from.
APPROVED_HOST = "telemetry.provue.internal"

# Dev-only shim: when running the services as local processes (no Docker DNS),
# the internal hostname `collector` does not resolve. This maps a parsed host
# to a real address *for the outbound connection only*, without changing the
# exploit URL. It is unset in the container topology, where Docker DNS resolves
# `collector` natively, so it never affects the shipped challenge semantics.
_DEV_HOST_ALIASES = json.loads(os.environ.get("DEV_HOST_ALIASES", "{}"))

RENDER_TIMEOUT = float(os.environ.get("RENDER_TIMEOUT", "4"))

LANDING = """<!doctype html>
<html lang="en">
<head><meta charset="utf-8"><title>Provue Telemetry Console</title></head>
<body>
  <h1>Provue Telemetry Console</h1>
  <p>Internal telemetry dashboard for the Provue edge fleet.</p>
  <p>Status: <strong>operational</strong></p>
  <!-- API surface is documented at /api/spec -->
</body>
</html>
"""


def _issue_token(claims):
    return jwt.encode(claims, JWT_SECRET, algorithm=JWT_ALG)


def _decode_token():
    auth = request.headers.get("Authorization", "")
    if not auth.startswith("Bearer "):
        return None
    token = auth[len("Bearer "):].strip()
    try:
        return jwt.decode(token, JWT_SECRET, algorithms=[JWT_ALG])
    except jwt.PyJWTError:
        return None


@app.get("/healthz")
def healthz():
    return "ok", 200


@app.get("/")
def index():
    return Response(LANDING, mimetype="text/html")


@app.get("/api/spec")
def spec():
    # S1 recon surface: documents the endpoints, the operator gate on render,
    # and the internal upstream (host + approved-source hostname).
    return jsonify(
        {
            "service": "provue-telemetry-console",
            "version": "2.3.0",
            "auth": {
                "scheme": "bearer-jwt",
                "issue": "POST /api/session  (body: {\"user\": \"<name>\"})",
                "introspect": "GET /api/whoami",
            },
            "endpoints": [
                {"path": "/api/session", "method": "POST", "auth": "none",
                 "desc": "issue a session token"},
                {"path": "/api/whoami", "method": "GET", "auth": "token",
                 "desc": "introspect the current token's claims"},
                {"path": "/api/reports/render", "method": "POST", "auth": "operator",
                 "desc": "render a report by fetching an approved telemetry source"},
                {"path": "/api/reports/publish", "method": "POST",
                 "auth": "operator + deploy-key",
                 "desc": "publish a signed report; requires the production deploy "
                         "key in the X-Deploy-Key header"},
            ],
            "upstreams": {
                "telemetry_store": "http://collector:9000",
                "approved_source_host": APPROVED_HOST,
            },
            "notes": "reports are generated by fetching the approved telemetry "
                     "source server-side and returning its contents",
        }
    )


@app.post("/api/session")
def session():
    body = request.get_json(silent=True) or {}

    # Baseline claims for a fresh session.
    claims = {"user": body.get("user", "guest"), "role": "viewer"}

    # VULN (mass assignment): the whole request body is merged over the claims,
    # so a caller can supply "role": "operator" (or any other claim) directly.
    for key, value in body.items():
        claims[key] = value

    return jsonify({"token": _issue_token(claims), "claims": claims})


@app.get("/api/whoami")
def whoami():
    claims = _decode_token()
    if claims is None:
        return jsonify({"error": "missing or invalid token"}), 401
    return jsonify({"claims": claims})


def _host_is_approved(source_url):
    # VULN (allowlist parser differential): this only checks that the approved
    # host appears *somewhere* in the URL string. A URL such as
    #   http://telemetry.provue.internal@collector:9000/metrics
    # contains the approved host as a userinfo component while the real
    # connection authority is `collector:9000`.
    return APPROVED_HOST in source_url


def _apply_dev_alias(source_url):
    parts = urlsplit(source_url)
    host = parts.hostname
    if host in _DEV_HOST_ALIASES:
        alias = _DEV_HOST_ALIASES[host]
        netloc = alias
        if parts.port:
            netloc = f"{alias}:{parts.port}"
        parts = parts._replace(netloc=netloc)  # drop userinfo for the local dial
        return urlunsplit(parts)
    return source_url


@app.post("/api/reports/render")
def render_report():
    claims = _decode_token()
    if claims is None:
        return jsonify({"error": "missing or invalid token"}), 401
    if claims.get("role") != "operator":
        return jsonify({"error": "operator role required to render reports"}), 403

    body = request.get_json(silent=True) or {}
    source = body.get("source", "")
    if not isinstance(source, str) or not source:
        return jsonify({"error": "body must include a string 'source' URL"}), 400

    scheme = urlsplit(source).scheme
    if scheme not in ("http", "https"):
        return jsonify({"error": "source scheme must be http or https"}), 400

    if not _host_is_approved(source):
        return (
            jsonify({"error": "source host is not approved",
                     "approved_host": APPROVED_HOST}),
            400,
        )

    dial_url = _apply_dev_alias(source)
    try:
        resp = requests.get(
            dial_url,
            headers={"X-Edge-Origin": EDGE_ORIGIN_TOKEN},
            timeout=RENDER_TIMEOUT,
            allow_redirects=False,
        )
    except requests.RequestException as exc:
        return jsonify({"error": "render failed", "detail": str(exc)}), 502

    return jsonify(
        {
            "source": source,
            "status": resp.status_code,
            "rendered": resp.text[:4000],
        }
    )


@app.post("/api/reports/publish")
def publish_report():
    claims = _decode_token()
    if claims is None:
        return jsonify({"error": "missing or invalid token"}), 401
    if claims.get("role") != "operator":
        return jsonify({"error": "operator role required to publish reports"}), 403

    # Final gate: the request must carry the production deploy key. The only way
    # to know it is to have exfiltrated it from the internal collector.
    presented = request.headers.get("X-Deploy-Key", "")
    if presented != DEPLOY_KEY:
        return (
            jsonify({"error": "invalid or missing deploy key",
                     "hint": "present the production deploy key in X-Deploy-Key"}),
            403,
        )

    return jsonify({"status": "published", "flag": FLAG})


if __name__ == "__main__":
    port = int(os.environ.get("PORT", "8080"))
    app.run(host="0.0.0.0", port=port)
