"""
Telemetry Console (edge service) — edge-pivot reference task.

Public-facing dashboard/API. Issues session tokens, exposes a small documented
API surface, renders a "report" by fetching an approved telemetry source
server-side, and publishes a signed report when given the production deploy key.

Intentionally vulnerable along three axes that must be chained:
  1. Session mass-assignment: token claims are built by merging the raw request
     body, so a caller can promote themselves to `operator`.
  2. Report-render SSRF: the approved-source allowlist is a naive substring
     check that a userinfo URL defeats, pivoting the fetch to the internal
     collector.
  3. Publish gate: the flag is only released to a caller who presents the
     production deploy key -- which must first be exfiltrated from the collector.

Secrets are derived from CRUCIBLE_SEED (per-instance unique, reproducible); the
collector derives the shared values identically. Explicit env vars override.
"""
import hashlib
import hmac
import json
import os
from urllib.parse import urlsplit, urlunsplit

import jwt
import requests
from flask import Flask, Response, jsonify, request

app = Flask(__name__)

SEED = os.environ.get("CRUCIBLE_SEED", "crucible-default")


def _derive(label, n):
    return hmac.new(SEED.encode(), label.encode(), hashlib.sha256).hexdigest()[:n]


JWT_SECRET = os.environ.get("JWT_SECRET") or ("jwt-" + _derive("jwt", 20))
JWT_ALG = "HS256"
EDGE_ORIGIN_TOKEN = os.environ.get("EDGE_ORIGIN_TOKEN") or ("edge-origin-" + _derive("edge-origin", 12))
DEPLOY_KEY = os.environ.get("DEPLOY_KEY") or ("k-" + _derive("deploy-key", 16))
FLAG = os.environ.get("FLAG") or ("flag{edge_pivot_" + _derive("flag", 12) + "}")

# The only host an operator is *supposed* to be able to render from.
APPROVED_HOST = "telemetry.internal.example"

# Dev-only shim: maps a parsed host to a real address for the outbound
# connection when running as local processes (no container DNS). Unset in the
# container topology, so it never affects the shipped challenge.
_DEV_HOST_ALIASES = json.loads(os.environ.get("DEV_HOST_ALIASES", "{}"))
RENDER_TIMEOUT = float(os.environ.get("RENDER_TIMEOUT", "4"))

LANDING = """<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Telemetry Console</title></head>
<body>
  <h1>Telemetry Console</h1>
  <p>Internal telemetry dashboard for the edge fleet.</p>
  <p>Status: <strong>operational</strong></p>
  <!-- API surface is documented at /api/spec -->
</body></html>
"""


def _issue_token(claims):
    return jwt.encode(claims, JWT_SECRET, algorithm=JWT_ALG)


def _decode_token():
    auth = request.headers.get("Authorization", "")
    if not auth.startswith("Bearer "):
        return None
    try:
        return jwt.decode(auth[7:].strip(), JWT_SECRET, algorithms=[JWT_ALG])
    except jwt.PyJWTError:
        return None


@app.get("/healthz")
def healthz():
    return "ok", 200


@app.get("/")
def index():
    return Response(LANDING, mimetype="text/html")


@app.get("/api/spec")
def spec():
    return jsonify({
        "service": "edge-telemetry-console",
        "version": "2.3.0",
        "auth": {"scheme": "bearer-jwt",
                 "issue": "POST /api/session  (body: {\"user\": \"<name>\"})",
                 "introspect": "GET /api/whoami"},
        "endpoints": [
            {"path": "/api/session", "method": "POST", "auth": "none",
             "desc": "issue a session token"},
            {"path": "/api/whoami", "method": "GET", "auth": "token",
             "desc": "introspect the current token's claims"},
            {"path": "/api/reports/render", "method": "POST", "auth": "operator",
             "desc": "render a report by fetching an approved telemetry source"},
            {"path": "/api/reports/publish", "method": "POST",
             "auth": "operator + deploy-key",
             "desc": "publish a signed report; requires the production deploy key "
                     "in the X-Deploy-Key header"},
        ],
        "upstreams": {"telemetry_store": "http://collector:9000",
                      "approved_source_host": APPROVED_HOST},
        "notes": "reports are generated by fetching the approved telemetry source "
                 "server-side and returning its contents",
    })


@app.post("/api/session")
def session():
    body = request.get_json(silent=True) or {}
    claims = {"user": body.get("user", "guest"), "role": "viewer"}
    # VULN (mass assignment): the whole body is merged over the claims.
    for key, value in body.items():
        claims[key] = value
    return jsonify({"token": _issue_token(claims), "claims": claims})


@app.get("/api/whoami")
def whoami():
    claims = _decode_token()
    if claims is None:
        return jsonify({"error": "missing or invalid token"}), 401
    return jsonify({"claims": claims})


def _host_is_approved(source_url):
    # VULN (allowlist parser differential): only checks that the approved host
    # appears somewhere in the URL string. A userinfo component satisfies it
    # while the real authority is elsewhere, e.g.
    #   http://telemetry.internal.example@collector:9000/metrics
    return APPROVED_HOST in source_url


def _apply_dev_alias(source_url):
    parts = urlsplit(source_url)
    if parts.hostname in _DEV_HOST_ALIASES:
        alias = _DEV_HOST_ALIASES[parts.hostname]
        netloc = f"{alias}:{parts.port}" if parts.port else alias
        return urlunsplit(parts._replace(netloc=netloc))
    return source_url


@app.post("/api/reports/render")
def render_report():
    claims = _decode_token()
    if claims is None:
        return jsonify({"error": "missing or invalid token"}), 401
    if claims.get("role") != "operator":
        return jsonify({"error": "operator role required to render reports"}), 403

    body = request.get_json(silent=True) or {}
    source = body.get("source", "")
    if not isinstance(source, str) or not source:
        return jsonify({"error": "body must include a string 'source' URL"}), 400
    if urlsplit(source).scheme not in ("http", "https"):
        return jsonify({"error": "source scheme must be http or https"}), 400
    if not _host_is_approved(source):
        return jsonify({"error": "source host is not approved",
                        "approved_host": APPROVED_HOST}), 400

    try:
        resp = requests.get(_apply_dev_alias(source),
                            headers={"X-Edge-Origin": EDGE_ORIGIN_TOKEN},
                            timeout=RENDER_TIMEOUT, allow_redirects=False)
    except requests.RequestException as exc:
        return jsonify({"error": "render failed", "detail": str(exc)}), 502

    return jsonify({"source": source, "status": resp.status_code,
                    "rendered": resp.text[:4000]})


@app.post("/api/reports/publish")
def publish_report():
    claims = _decode_token()
    if claims is None:
        return jsonify({"error": "missing or invalid token"}), 401
    if claims.get("role") != "operator":
        return jsonify({"error": "operator role required to publish reports"}), 403
    # Final gate: only a caller who has exfiltrated the deploy key can pass.
    if request.headers.get("X-Deploy-Key", "") != DEPLOY_KEY:
        return jsonify({"error": "invalid or missing deploy key",
                        "hint": "present the production deploy key in X-Deploy-Key"}), 403
    return jsonify({"status": "published", "flag": FLAG})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=int(os.environ.get("PORT", "8080")))
